name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'  # This is optional. It ignores changes to markdown files.
  push:
    branches:
      - master

jobs:
  build:
    if: github.event_name == 'pull_request' && github.head_ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debugging
        run: |
          ls -la
          python --version
          cat Pipfile.lock

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-v2-${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Python Lint
        run: |
          pipenv run lint

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ai3labsnews"
          heroku_email: "riharex420@gmail.com"
          branch: master
